version: "3"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env.db
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
  recipe:
    container_name: recipes
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./media:/vol/web/media
      - ./mysite:/usr/src/mysite
    # command: >
    #     sh -c "tail -F anything"
    command: >
      sh -c "python manage.py makemigrations && python manage.py migrate
          python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
