# Generated by Django 3.1.7 on 2021-04-11 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0005_auto_20210410_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='tag',
            field=models.ManyToManyField(to='recipe.Tag'),
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nazwa')),
                ('calories', models.IntegerField(blank=True, default=0, null=True, verbose_name='Kalorie')),
                ('portions', models.IntegerField(blank=True, null=True, verbose_name='Porcje')),
                ('prepare_time', models.IntegerField(blank=True, default=0, null=True, verbose_name='Czas przygotowania')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, default='', max_length=3000, verbose_name='Przygotowanie')),
                ('tag', models.ManyToManyField(to='recipe.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slug')},
            },
        ),
    ]
