# Generated by Django 3.1.7 on 2021-04-13 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0008_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='quantity',
            field=models.CharField(max_length=25),
        ),
    ]
