# Generated by Django 3.1.7 on 2021-04-14 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0010_auto_20210413_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='tag',
            new_name='tags',
        ),
    ]
