# Generated by Django 3.1.7 on 2021-04-14 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0012_testmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
