# Generated by Django 3.1.7 on 2021-04-15 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0013_delete_testmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='ingredients_quantity', through='recipe.Recipe_Ingredient', to='recipe.Ingredient'),
        ),
    ]
