# Generated by Django 3.1.7 on 2021-05-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0016_auto_20210505_1458'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set(),
        ),
    ]
