# Generated by Django 3.1.7 on 2021-05-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0017_auto_20210505_1531'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_user_name'),
        ),
    ]
