# Generated by Django 3.1.7 on 2021-05-06 07:42

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0020_auto_20210505_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo1',
            field=models.ImageField(blank=True, upload_to=recipe.models.recipe_image_file_path, verbose_name='Zdjęcie 1'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo2',
            field=models.ImageField(blank=True, upload_to=recipe.models.recipe_image_file_path, verbose_name='Zdjęcie 2'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo3',
            field=models.ImageField(blank=True, upload_to=recipe.models.recipe_image_file_path, verbose_name='Zdjęcie 3'),
        ),
    ]
