# Generated by Django 3.1.7 on 2021-06-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0023_auto_20210610_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='type',
            field=models.CharField(choices=[('S', 'solid'), ('L', 'liquid')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
