# Generated by Django 3.1.7 on 2021-06-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0027_auto_20210610_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.FloatField(null=True),
        ),
    ]
