# Generated by Django 3.1.7 on 2021-06-10 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0029_auto_20210610_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='unit_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.unit'),
        ),
    ]
