# Generated by Django 3.1.7 on 2021-06-10 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0030_auto_20210610_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe_ingredient',
            old_name='unit_id',
            new_name='unit',
        ),
    ]
