# Generated by Django 3.1.7 on 2021-06-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0031_auto_20210610_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
