# Generated by Django 3.1.7 on 2021-06-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0033_auto_20210610_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient',
            name='quantity',
        ),
    ]
