# Generated by Django 3.1.7 on 2021-06-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0034_remove_recipe_ingredient_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='carbohydrates',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fats',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='proteins',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
