# Generated by Django 3.1.7 on 2021-06-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0035_auto_20210611_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='calcium',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='fiber',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='iron',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='magnesium',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='potassium',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='selenium',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='sodium',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='zinc',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
