# Generated by Django 3.1.7 on 2021-06-15 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0041_auto_20210615_0740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='tag',
            new_name='tags',
        ),
    ]
