# Generated by Django 3.1.7 on 2021-06-17 19:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0042_auto_20210615_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(1, 'Value                         must be greater then 0!')]),
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='unit',
        ),
        migrations.CreateModel(
            name='Ingredient_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grams_in_one_unit', models.PositiveSmallIntegerField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.unit')),
            ],
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.ManyToManyField(through='recipe.Ingredient_Unit', to='recipe.Unit'),
        ),
    ]
