# Generated by Django 3.1.7 on 2021-06-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0043_auto_20210617_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='unit',
            new_name='units',
        ),
        migrations.AlterField(
            model_name='ingredient_unit',
            name='grams_in_one_unit',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
