# Generated by Django 3.1.7 on 2021-07-13 13:34

from django.db import migrations, models
import recipe.models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0046_auto_20210621_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='photo1',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.recipe_image_file_path, verbose_name='Zdjęcie 1'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.recipe_image_file_path, verbose_name='Zdjęcie 2'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to=recipe.models.recipe_image_file_path, verbose_name='Zdjęcie 3'),
        ),
    ]
