# Generated by Django 3.1.7 on 2021-07-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0047_auto_20210713_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='carbohydrates',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='fats',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='proteins',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
