# Generated by Django 3.1.7 on 2021-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0048_auto_20210713_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='calories',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Kalorie'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='carbohydrates',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='fats',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='proteins',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
