# Generated by Django 3.1.7 on 2021-07-29 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0049_auto_20210714_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recipe.unit'),
        ),
    ]
