# Generated by Django 3.1.7 on 2021-07-29 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0050_auto_20210729_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='recipe.unit'),
        ),
    ]
