# Generated by Django 3.1.7 on 2021-07-29 13:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0051_auto_20210729_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories',
            field=models.FloatField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1, 'Value                         must be greater then 0!')]),
        ),
    ]
