# Generated by Django 3.1.7 on 2021-08-07 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0052_auto_20210729_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyMeals',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('recipe.ingredient',),
        ),
    ]
