# Generated by Django 3.1.7 on 2021-09-09 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0055_auto_20210909_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='_usage_counter',
        ),
    ]
