# Generated by Django 3.1.7 on 2021-09-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0056_remove_ingredient__usage_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
