# Generated by Django 3.1.7 on 2021-09-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0055_auto_20210909_1155 2'),
        ('recipe', '0057_auto_20210916_1111 2'),
        ('recipe', '0057_auto_20210916_1111'),
    ]

    operations = [
    ]
