# Generated by Django 3.1.7 on 2021-11-26 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0059_auto_20210926_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='recipe.unit'),
            preserve_default=False,
        ),
    ]
