# Generated by Django 3.1.7 on 2021-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0061_auto_20211128_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Przygotowanie'),
        ),
    ]
