# Generated by Django 3.1.7 on 2021-05-11 14:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
