# Generated by Django 3.1.7 on 2021-05-12 10:04

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210512_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(null=True, max_length=100),
        ),
    ]
