# Generated by Django 3.1.7 on 2021-05-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20210522_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Podany adres email jest zajęty'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(error_messages={'unique': 'Podana nazwa jest zajęta'}, max_length=255, unique=True),
        ),
    ]
