# Generated by Django 3.1.7 on 2021-07-26 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210526_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founder', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
