# Generated by Django 3.1.7 on 2021-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210608_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.AddField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6),
        ),
    ]
