# Generated by Django 3.1.7 on 2021-08-07 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210710_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='founder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_group', to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
