# Generated by Django 3.1.7 on 2021-08-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210807_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='strava_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
