# Generated by Django 3.1.7 on 2021-08-12 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_myuser_strava_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='strava_code',
        ),
        migrations.CreateModel(
            name='StravaTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(max_length=255)),
                ('expires_at', models.PositiveIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='strava', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
