# Generated by Django 3.1.7 on 2021-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210812_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravatokens',
            name='expires_at',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
