# Generated by Django 3.1.7 on 2021-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210830_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='StravaTokens',
            name='last_update',
            field=models.FloatField(default=0),
        ),
    ]
