# Generated by Django 3.1.7 on 2021-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_stravatokens_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravatokens',
            name='valid',
            field=models.BooleanField(default=False),
        ),
    ]
