# Generated by Django 3.1.7 on 2021-09-01 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210901_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='StravaTokens',
            name='valid',
        ),
    ]
