# Generated by Django 3.1.7 on 2021-09-02 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210902_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='stravaactivity',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
