# Generated by Django 3.1.7 on 2021-09-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20210902_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
