# Generated by Django 3.1.7 on 2021-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20210902_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='calories',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='stravaactivity',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
