# Generated by Django 3.1.7 on 2021-09-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210902_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='strava_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
