# Generated by Django 3.1.7 on 2021-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210903_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stravaactivity',
            name='strava_id',
            field=models.PositiveBigIntegerField(unique=True),
        ),
    ]
