# Generated by Django 3.1.7 on 2021-09-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210726_1445'),
        ('users', '0034_auto_20210903_1347'),
    ]

    operations = [
    ]
