# Generated by Django 3.1.7 on 2021-09-22 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_auto_20210909_0818'),
        ('users', '0036_auto_20210909_0818 2'),
        ('users', '0011_auto_20210726_1444 2'),
        ('users', '0035_merge_20210909_0807 2'),
        ('users', '0012_auto_20210726_1445 2'),
    ]

    operations = [
    ]
