# Generated by Django 3.1.7 on 2021-11-28 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20210928_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email not available'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='name',
            field=models.CharField(error_messages={'unique': 'Name not available'}, max_length=255, unique=True),
        ),
    ]
