# Generated by Django 3.1.7 on 2021-05-27 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('health', '0003_auto_20210526_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='healthdiary',
            unique_together={('date', 'user')},
        ),
    ]
