# Generated by Django 3.1.7 on 2021-05-28 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_auto_20210527_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
