# Generated by Django 3.1.7 on 2021-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_healthdiary_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='kalorie'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='rest_heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='tetno'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='sleep_length',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='sen'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='waga'),
        ),
    ]
