# Generated by Django 3.1.7 on 2021-07-10 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20210608_0855'),
        ('health', '0008_auto_20210607_1153'),
    ]

    operations = [
    ]
