# Generated by Django 3.1.7 on 2021-08-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_merge_20210710_0701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='kalorie'),
        ),
    ]
