# Generated by Django 3.1.7 on 2021-08-11 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_auto_20210811_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='kalorie'),
        ),
    ]
