# Generated by Django 3.1.7 on 2021-08-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20210811_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1628860296.7326324),
        ),
    ]
