# Generated by Django 3.1.7 on 2021-08-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_auto_20210830_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630329379.4662936),
        ),
    ]
