# Generated by Django 3.1.7 on 2021-08-31 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0015_auto_20210831_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630412621.4451754),
        ),
    ]
