# Generated by Django 3.1.7 on 2021-09-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_auto_20210831_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630476418.263989),
        ),
    ]
