# Generated by Django 3.1.7 on 2021-09-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0017_auto_20210901_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630480800.5150223),
        ),
    ]
