# Generated by Django 3.1.7 on 2021-09-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0018_auto_20210901_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630501659.6504626),
        ),
    ]
