# Generated by Django 3.1.7 on 2021-09-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0019_auto_20210901_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630580984.440594),
        ),
    ]
