# Generated by Django 3.1.7 on 2021-09-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0020_auto_20210902_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdiary',
            name='burned_calories',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='calories',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='calories'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630582563.1987424),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='rest_heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=None, null=True, verbose_name='heart rate'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='sleep_length',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='sleep'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='weigth'),
        ),
    ]
