# Generated by Django 3.1.7 on 2021-09-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0021_auto_20210902_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630591338.1408162),
        ),
    ]
