# Generated by Django 3.1.7 on 2021-09-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0025_auto_20210902_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630607395.2867212),
        ),
    ]
