# Generated by Django 3.1.7 on 2021-09-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0028_auto_20210902_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630609762.3410437),
        ),
    ]
