# Generated by Django 3.1.7 on 2021-09-03 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0029_auto_20210902_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630655644.864864),
        ),
    ]
