# Generated by Django 3.1.7 on 2021-09-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0032_auto_20210903_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630664146.2517812),
        ),
    ]
