# Generated by Django 3.1.7 on 2021-09-03 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0033_auto_20210903_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630670986.034642),
        ),
    ]
