# Generated by Django 3.1.7 on 2021-09-03 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0034_auto_20210903_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630676851.652235),
        ),
    ]
