# Generated by Django 3.1.7 on 2021-09-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0035_auto_20210903_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1630778568.5738912),
        ),
    ]
