# Generated by Django 3.1.7 on 2021-09-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0037_auto_20210907_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1631085438.692897),
        ),
    ]
