# Generated by Django 3.1.7 on 2021-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0039_auto_20210908_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='last_update',
            field=models.PositiveIntegerField(default=1631085763.1444545),
        ),
    ]
