# Generated by Django 3.1.7 on 2021-09-09 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0042_auto_20210908_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='sleep_length',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
