# Generated by Django 3.1.7 on 2021-09-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0043_auto_20210909_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='rest_heart_rate',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='heart rate'),
        ),
        migrations.AlterField(
            model_name='healthdiary',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='weigth'),
        ),
    ]
