# Generated by Django 3.1.7 on 2021-10-05 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0044_auto_20210911_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='weigth'),
        ),
    ]
