# Generated by Django 3.1.7 on 2021-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0045_auto_20211005_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='daily_thoughts',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
    ]
