# Generated by Django 3.1.7 on 2021-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0046_auto_20211005_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdiary',
            name='daily_thoughts',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
