# Generated by Django 3.1.7 on 2021-06-07 11:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0022_ingredient__usage_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('calories', models.PositiveSmallIntegerField(blank=True, default=None, null=True)),
                ('recipes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
