# Generated by Django 3.1.7 on 2021-06-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='recipes',
            new_name='recipe',
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
