# Generated by Django 3.1.7 on 2021-06-07 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0002_auto_20210607_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
