# Generated by Django 3.1.7 on 2021-06-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0003_auto_20210607_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='name',
        ),
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
