# Generated by Django 3.1.7 on 2021-06-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0007_auto_20210608_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipe_portions',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
