# Generated by Django 3.1.7 on 2021-06-08 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0022_ingredient__usage_counter'),
        ('meals_tracker', '0008_meal_recipe_portions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal', to='meals_tracker.mealcategory'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipe.recipe'),
        ),
    ]
