# Generated by Django 3.1.7 on 2021-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0009_auto_20210608_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='recipe_portions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
