# Generated by Django 3.1.7 on 2021-07-19 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0049_auto_20210714_0927'),
        ('meals_tracker', '0010_auto_20210608_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='recipe_portions',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='recipe',
        ),
        migrations.CreateModel(
            name='RecipePortion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portion', models.PositiveSmallIntegerField()),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meals_tracker.meal')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='recipe',
            field=models.ManyToManyField(blank=True, null=True, through='meals_tracker.RecipePortion', to='recipe.Recipe'),
        ),
    ]
