# Generated by Django 3.1.7 on 2021-07-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0049_auto_20210714_0927'),
        ('meals_tracker', '0012_auto_20210720_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredient',
            field=models.ManyToManyField(through='meals_tracker.IngredientAmount', to='recipe.Ingredient'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='recipe',
            field=models.ManyToManyField(through='meals_tracker.RecipePortion', to='recipe.Recipe'),
        ),
    ]
