# Generated by Django 3.1.7 on 2021-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0013_auto_20210720_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeportion',
            name='portion',
            field=models.PositiveSmallIntegerField(default=1, null=True),
        ),
    ]
