# Generated by Django 3.1.7 on 2021-07-20 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0049_auto_20210714_0927'),
        ('meals_tracker', '0015_auto_20210720_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeportion',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe'),
        ),
    ]
