# Generated by Django 3.1.7 on 2021-07-21 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0016_auto_20210720_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='ingredient',
            new_name='ingredients',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='recipe',
            new_name='recipes',
        ),
        migrations.AlterField(
            model_name='recipeportion',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes_extra_info', to='meals_tracker.meal'),
        ),
        migrations.AlterField(
            model_name='recipeportion',
            name='portion',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
