# Generated by Django 3.1.7 on 2021-07-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0017_auto_20210721_1006'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeportion',
            constraint=models.UniqueConstraint(fields=('meal', 'recipe'), name='unique recipe-meal'),
        ),
    ]
