# Generated by Django 3.1.7 on 2021-07-23 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0018_auto_20210722_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='calories',
        ),
    ]
