# Generated by Django 3.1.7 on 2021-07-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals_tracker', '0020_meal_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealcategory',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
